CREATE TABLE IF NOT EXISTS withdrawals (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  chain VARCHAR(20) NOT NULL,
  asset VARCHAR(30) NOT NULL,
  currency VARCHAR(30) NOT NULL,
  to_address CHAR(42) NOT NULL,
  amount_minor VARCHAR(80) NOT NULL,
  fee_minor VARCHAR(80) NOT NULL DEFAULT '0',
  status VARCHAR(30) NOT NULL,
  idempotency_key VARCHAR(120) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  hold_reference VARCHAR(190) NOT NULL,
  tx_hash CHAR(66) NULL,
  nonce BIGINT NULL,
  error_code VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_withdraw_idem (user_id, idempotency_key),
  UNIQUE KEY uniq_withdraw_holdref (hold_reference),
  KEY idx_withdraw_status (status),
  KEY idx_withdraw_user (user_id),
  CONSTRAINT fk_withdraw_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;
